### PR TITLE
Update to work under O1.10.x and updated JQuery datetime stuff

### PR DESCRIPTION
**Pull request by MatteoPiovanelli-Laser**
- Loaded the project in an O1.10.x fork and made it work there.
- Updated NuGet stuff.
- Fixed the jQuery things from #77.
- A lot of the diff on the csproj file has to do with the fact that I have a different folder setup than canon, hence I had to use a script to fix the csproj so it would work on the normal folder structure. If someone could please give it a look to make sure I didn't miss anything it would be great.

Besides the issue I have with keeping the csproj aligned, everything should be pretty straightforward. If this looks ok I can start working on the other bugs and enhancements.

### CODE REVIEW

**Comment by bleroy** [comment]
Thanks!

**Comment by MatteoPiovanelli-Laser** [comment]
Just to make sure, did you verify that everything works on your end? What the script does to fix the csproj _should_ be fine, but I couldn't test it on my end.

**Comment by bleroy** [comment]
Not yet. It looks low-risk until I include the change in a release, so I prefer to take the PR if that can unblock people who need it. Thanks again for the contribution.

**Comment by MatteoPiovanelli-Laser** [comment]
No problem. I'll be working on a few more PRs in the near future.

**Pull request merged**
