### PR TITLE
Inventory synchronization

### PR DESCRIPTION
**Pull request by MatteoPiovanelli-Laser**
based on #101 I wrote code to synchronize the inventory across products with the same sku (as a feature that needs activating).

This PR as of now is not complete.
For example, it still needs the method to verify that inventories are "fine" when activating the feature, and I think this PR as it is would break some tests (I haven't checked) because I changed the constructors of some controllers.

However, I am putting this out there to allow reviewing what's already there.

### CODE REVIEW

**Comment by MatteoPiovanelli-Laser** [comment]
I think this feature is complete as it is in the PR.

**Comment by bleroy** [comment]
I can't merge it right now: there are conflicts.

**Comment by MatteoPiovanelli-Laser** [comment]
Fixed conflicts by merging master back in

**Comment by bleroy** [comment]
Still has conflicts, maybe because I just merged another of your PRs.

**Comment by MatteoPiovanelli-Laser** [comment]
Yes. Those are from the double-to-decimal pr. I'll fix those and upgrade the handler from there to use the product services

**Comment by MatteoPiovanelli-Laser** [comment]
I updated things to use the services.

**Pull request merged**
