### PR TITLE
Enhancement for digital product inventory

### PR DESCRIPTION
**Pull request by MatteoPiovanelli-Laser**
This is the PR I talked about in #97 
Note that this includes what's been done in #96.

Merging this should wait until that is in, or if that will not be pulled some code in this should change, namely the migrations for `ProductPartRecord`

### CODE REVIEW

**Comment by MatteoPiovanelli-Laser** [comment]
I removed the "dependency" on #96 by rebasing on the master branch, so this does not require the part that's been done to convert all prices to decimal

**Comment by bleroy** [comment]
Can you also resolve conflicts? I can't merge it as it is. Thanks!

**Comment by MatteoPiovanelli-Laser** [comment]
It should be fine now

**Comment by bleroy** [comment]
Thanks!

**Pull request merged**
